### ISSUE TITLE
problem with the loadDir

### ISSUE THREAD

**Issue by Yi-ChingChen** [puzzledqs/BBox-Label-Tool#1]
i can't load my picture 
s = r'D:\workspace\python\labelGUI' <= is that image's path??
coz I use in anaconda and i wander know how to set the image's path.

**Comment by puzzledqs** [comment]
labelGui is actually the root path. Try put your images under labelGUI/Images.

**Comment by DaVinciZhu** [comment]
if my picture is too big, it cannot show all. i wander know how to change the picture's size?

**Comment by yueyeyuniao** [comment]
Hi, I tried to load Image/002 folder, the images did not show up.  (1 works for me)

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "main.py", line 264, in prevImage
    self.saveImage()
  File "main.py", line 202, in saveImage
    with open(self.labelfilename, 'w') as f:
IOError: [Errno 2] No such file or directory: ''

So, how can I use the images in 002 folder? Thx

**Comment by bexx1963** [comment]
You can load images from folder 002, 003 and so on when you create empty folders in directory example with same name 002, 003 and so on
