### ISSUE TITLE
Bad color names in multi-label branch

### ISSUE THREAD

**Issue by renxinhe** [puzzledqs/BBox-Label-Tool#24]
`olive` and `teal` are not accepted color names. The third and fourth bounding boxes don't show up as a result of this. [main.py line 19](https://github.com/puzzledqs/BBox-Label-Tool/blob/multi-class/main.py#L19) need to be modified to include valid [Tkinter colors](https://wiki.tcl.tk/37701).

**Comment by DennisFaucher** [comment]
Same

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1547, in __call__
    return self.func(*args)
  File "main.py", line 296, in prevImage
    self.loadImage()
  File "main.py", line 223, in loadImage
    outline = COLORS[(len(self.bboxList)-1) % len(COLORS)])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 2337, in create_rectangle
    return self._create('rectangle', args, kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 2316, in _create
    *(args + self._options(cnf, kw))))
TclError: unknown color name "olive"
