### ISSUE TITLE
Problem in LoadDir

### ISSUE THREAD

**Issue by alfamousts** [puzzledqs/BBox-Label-Tool#31]
when i try to press the load button, in command line shows error like this

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "main.py", line 126, in loadDir
    self.category = int(s)
ValueError: invalid literal for int() with base 10: ''
```

anyone can help me solve this problem ?

**Comment by RameshKamath** [comment]
In BBox-Label-Tool/Images there should be "001" folder. Create a new folder with name "002" and put all your images into this folder (for Image Dir box near load button give 2).

Your images should have extension of JPG (for that in Images folders terminal give `mogrify -format JPG 002/*.jpg`)

**Comment by maxiujin** [comment]
This does not help what is the answer??

**Comment by hemanths933** [comment]
The tool is expecting only an integer as @RameshKamath has mentioned. If any character other than number is entered in Image Dir in the tool, then the exception occurs as below:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "main.py", line 126, in loadDir
    self.category = int(s)
ValueError: invalid literal for int() with base 10: ''
